<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2019-10-03T00:00:21 IST" name="Default suite" finished-at="2019-10-03T00:00:23 IST" duration-ms="2637">
    <groups>
    </groups>
    <test started-at="2019-10-03T00:00:21 IST" name="Default test" finished-at="2019-10-03T00:00:23 IST" duration-ms="2637">
      <class name="reporting.ExtentReport">
        <test-method is-config="true" signature="startReport()[pri:0, instance:reporting.ExtentReport@609db43b]" started-at="2019-10-03T00:00:21 IST" name="startReport" finished-at="2019-10-03T00:00:22 IST" duration-ms="1384" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startReport -->
        <test-method signature="demoReportFail()[pri:0, instance:reporting.ExtentReport@609db43b]" started-at="2019-10-03T00:00:22 IST" name="demoReportFail" finished-at="2019-10-03T00:00:22 IST" duration-ms="73" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[did not expect to find [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at reporting.ExtentReport.demoReportFail(ExtentReport.java:46)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1378)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- demoReportFail -->
        <test-method is-config="true" signature="getReport(org.testng.ITestResult)[pri:0, instance:reporting.ExtentReport@609db43b]" started-at="2019-10-03T00:00:22 IST" name="getReport" finished-at="2019-10-03T00:00:22 IST" duration-ms="18" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=demoReportFail status=FAILURE method=ExtentReport.demoReportFail()[pri:0, instance:reporting.ExtentReport@609db43b] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getReport -->
        <test-method signature="demoReportPass()[pri:0, instance:reporting.ExtentReport@609db43b]" started-at="2019-10-03T00:00:22 IST" name="demoReportPass" finished-at="2019-10-03T00:00:22 IST" duration-ms="4" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- demoReportPass -->
        <test-method is-config="true" signature="getReport(org.testng.ITestResult)[pri:0, instance:reporting.ExtentReport@609db43b]" started-at="2019-10-03T00:00:22 IST" name="getReport" finished-at="2019-10-03T00:00:22 IST" duration-ms="0" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=demoReportPass status=SUCCESS method=ExtentReport.demoReportPass()[pri:0, instance:reporting.ExtentReport@609db43b] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getReport -->
        <test-method is-config="true" signature="endReport()[pri:0, instance:reporting.ExtentReport@609db43b]" started-at="2019-10-03T00:00:22 IST" name="endReport" finished-at="2019-10-03T00:00:23 IST" duration-ms="1000" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endReport -->
      </class> <!-- reporting.ExtentReport -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
